version: '3.7'

services:
  member:
    image: "scaleout/member:latest"
    environment:
      - GET_HOSTS_FROM=dns
    command: sh ./run.sh
    volumes:
      - ./member:/app
      - ./member/data:/app/data

